services:
- type: web
  name: nextjs-static
  runtime: static
  buildCommand: pnpm; pnpm build
  staticPublishPath: out
  pullRequestPreviewsEnabled: true     # optional
  envVars:
  - key: NODE_ENV
    value: production