name: Sync .env.example to Docker config repo

on:
  push:
    branches:
      - master
    paths:
      - '.env.example'

jobs:
  sync-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Service Repository (Repo B)
        uses: actions/checkout@v4

      - name: Clone Docker Config Repository (school-admin)
        run: |
          git clone https://x-oauth-basic:${{ secrets.SCHOOL_ADMIN_SCRECT }}@github.com/buddhagrg/school-admin.git school-admin-clone
        env:
          SCHOOL_ADMIN_SCRECT: ${{ secrets.SCHOOL_ADMIN_SCRECT }}

      - name: Create frontend-next directory and copy .env.example as .env
        run: |
          cd school-admin-clone
          echo "Creating directory: ./frontend-next"
          mkdir -p ./frontend-next
          echo "Copying ../.env.example to ./frontend-next/.env"
          cp ../.env.example ./frontend-next/.env

      - name: Configure Git and Push changes to Docker Config Repository
        run: |
          cd school-admin-clone
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Git configuration set for school-admin."

          git add ./frontend-next/.env

          if ! git diff-index --quiet HEAD; then
            echo "Committing changes to school-admin..."
            git commit -m "Update .env from service repo workflow"
            echo "Pushing changes to school-admin..."
            git push
            echo "Changes pushed successfully to school-admin."
          else
            echo "No changes detected in .env for school-admin, skipping commit and push."
          fi
